# -*- coding: utf-8 -*-
import os

# --- 全局配置 ---
SUPPORTED_EXTENSIONS = ['.jpg', '.jpeg', '.png', '.bmp', '.tiff', '.tif']
RUN_STATE_DIR = 'run_state' # 相对于运行 main.py 的目录
GLOBAL_LOG_FILE_PATH = os.path.join(RUN_STATE_DIR, 'compression.log')

# --- 原格式压缩模式特定配置 ---
INPLACE_DIR_STATE_FILE_NAME = '.processed_files_original.log'
INPLACE_DIR_LOG_FILE_NAME = '_folder_compression_original.log'
INPLACE_DEFAULT_COMPRESSION_QUALITY = 85
INPLACE_DEFAULT_PNG_OPTIMIZE = True
INPLACE_LARGE_FILE_THRESHOLD_MB = 15
INPLACE_LARGE_FILE_COMPRESSION_QUALITY = 75

# --- WebP 模式特定配置 ---
WEBP_DIR_STATE_FILE_NAME = '.processed_files_webp.log'
WEBP_DIR_LOG_FILE_NAME = '_folder_webp.log'
WEBP_DEFAULT_QUALITY = 85
WEBP_DEFAULT_LOSSLESS = False # False 表示默认有损，但PNG/BMP/TIFF会倾向无损

# --- 多语言文本 ---
# (保持和原文件完全一致的 texts 字典)
texts = {
    'zh': {
        # --- 通用 & 设置 ---
        "select_language": "请选择语言 (1=中文, 2=English, 默认: 中文): ",
        "invalid_choice_language": "无效的选择，请输入 1 或 2 或直接按 Enter。",
        "language_selected": "已选择语言: 中文",
        "select_mode": "请选择处理模式 (1=原格式压缩, 2=转换为WebP, 默认: 转换为WebP): ",
        "invalid_choice_mode": "无效的选择，请输入 1 或 2 或直接按 Enter。",
        "mode_selected": "已选择处理模式: {mode_name}",
        "mode_webp": "转换为 WebP (替换)",
        "mode_inplace": "原格式压缩 (保留格式并替换)",
        "prompt_jpeg_quality": "请输入 JPEG 压缩质量 (1-95, 默认: {default}): ",
        "prompt_png_optimize": "是否启用 PNG 优化? (y/n, 默认: {default}): ",
        "prompt_webp_quality": "请输入 WebP 压缩质量/强度 (0-100, 默认: {default}): ",
        "prompt_webp_lossless": "是否强制使用 WebP 无损模式? (y/n, 默认: {default}): ",
        "error_invalid_quality_jpeg": "质量必须在 1 到 95 之间。",
        "error_invalid_quality_webp": "质量必须在 0 到 100 之间。",
        "error_invalid_number": "请输入有效的数字。",
        "error_invalid_yn": "请输入 'y' 或 'n'。",
        "user_interrupt": "用户中断输入。",
        "task_start": "="*30 + " 开始执行图片处理任务 (模式: {mode_name}) " + "="*30,
        "target_folder": "目标根目录: {folder}",
        "supported_types": "支持的文件类型: {extensions}",
        "inplace_config": "原格式压缩模式配置: JPEG 质量={quality}, 大文件(>{large_threshold}MB)质量={large_quality}, PNG 优化={png_optimize}",
        "inplace_png_optimize_enabled": "启用",
        "inplace_png_optimize_disabled": "禁用",
        "webp_config": "WebP 转换模式配置: 质量={quality}, {lossless_mode}",
        "webp_config_lossless_forced": "强制无损",
        "webp_config_lossless_auto": "默认有损(PNG/BMP/TIFF倾向无损)",
        "state_file_info": "目录状态文件: {state_file}, 目录日志: {log_file}",
        "scanning_dir": "扫描目录 ({mode_name} 模式): {subdir}",
        "dir_processed_count": "目录 {subdir} 已处理文件数 (来自状态文件 {state_file}): {count}",
        "skip_webp_self": "跳过 WebP 文件自身: {path}",
        "unhandled_exception": "调用处理函数时捕获到未处理异常 ({path}): {error}",
        "dir_process_complete": "在目录 {subdir} 中成功完成 {count} 个文件的 {mode_name} 处理。",
        "user_interrupt_process": "用户中断了处理过程。",
        "unexpected_error_process": "处理过程中发生未预料的错误。",
        "task_end": "="*30 + " 图片处理任务结束 (模式: {mode_name}) " + "="*30,
        "summary_processed": "本次运行成功处理文件总数: {count}",
        "summary_skipped": "本次运行因已处理而跳过的文件总数: {count}",
        "summary_dirs_processed": "本次运行共在 {count} 个目录下执行了处理操作。",
        "summary_errors": "本次运行遇到错误或未能成功处理的文件总数: {count}",
        "summary_size_before": "处理前文件总体积 (估算): {size:.2f} MB",
        "summary_size_after": "处理后文件总体积: {size:.2f} MB",
        "summary_reduction": "总体积减少约: {percent:.2f}%",
        "summary_no_output": "未成功生成任何输出文件，无法计算体积减少百分比。",
        "summary_duration": "任务总耗时: {duration:.2f} 秒",
        "summary_global_log": "全局日志请查看: {path}",
        "summary_dir_log": "{mode_name} 模式的目录日志请查看对应目录下的 {log_file} 文件。",
        "summary_dir_state": "{mode_name} 模式的状态记录请查看对应目录下的 {state_file} 文件。",
        "error_invalid_path": "错误：提供的路径 '{path}' 不是一个有效的目录或无法访问。",
        "argparse_description": "图片处理工具：递归处理指定目录及其子目录中的图片。\n"
                                "启动后选择处理模式 (默认 WebP 转换, 可选原格式压缩) 和参数。\n"
                                "支持断点续处理，使用目录级状态文件和日志。",
        "argparse_folder_help": "需要处理的图片根文件夹路径",
        # --- 日志和处理函数中的文本 ---
        "log_setup_fail": "错误：无法设置全局日志文件处理器于 {path}: {error}",
        "log_dir_write_fail": "写入目录日志 {path} 失败: {error}",
        "log_load_state_success": "成功从 {path} 加载 {count} 条记录",
        "log_load_state_fail": "加载目录状态文件 {path} 时出错: {error}",
        "log_save_state_fail": "追加记录到目录状态文件 {path} 时出错 (原始文件名: {filename}): {error}",
        # --- 原格式压缩模式特定日志 ---
        "compress_skip_processed": "跳过已处理文件 (根据目录状态 {state_file}): {path}",
        "compress_start": "开始原格式压缩处理: {filename}",
        "compress_start_path": "开始原格式压缩处理: {path}",
        "compress_file_size": "文件大小: {size:.2f} MB",
        "compress_get_size_fail": "无法获取文件大小 {filename}: {error}",
        "compress_get_size_fail_path": "无法获取文件大小 {path}: {error}",
        "compress_open_success": "成功打开图片: {path}",
        "compress_format_unknown": "无法确定图片格式 (扩展名: {ext})，跳过处理: {filename}",
        "compress_format_unknown_path": "无法确定图片格式: {path} (扩展名: {ext})，跳过处理。",
        "compress_format_identified": "识别到图片格式: {format} for {path}",
        "compress_large_file": "检测到大文件 (> {threshold} MB)，应用特殊压缩质量: {quality}",
        "compress_large_file_log": "{filename} - 检测到大文件 (> {threshold} MB)，应用特殊压缩质量: {quality}",
        "compress_rgba_to_rgb": "图片 {path} 是 RGBA 模式，将转换为 RGB 后保存为 JPEG。",
        "compress_rgba_to_rgb_log": "图片 {filename} 是 RGBA 模式，将转换为 RGB。",
        "compress_default_save": "使用默认设置按原格式 {format} 保存: {path}",
        "compress_save_temp_success": "图片成功压缩/保存到临时文件: {path}",
        "compress_temp_invalid": "压缩/保存结果无效（临时文件不存在或为空），原图 {filename} 不会被删除。",
        "compress_temp_invalid_path": "压缩/保存结果无效: {path}，原图 {original_path} 不会被删除。",
        "compress_temp_clean_fail": "清理无效临时文件 {path} 时失败: {error}",
        "compress_remove_original_success": "成功删除原图: {path}",
        "compress_remove_original_fail": "删除原图 {filename} 时失败: {error}。压缩/保存后的文件 {temp_filename} 将被保留。",
        "compress_remove_original_fail_path": "删除原图 {path} 时失败: {error}。临时文件 {temp_path} 被保留。",
        "compress_rename_success": "原格式压缩成功: {filename} (原: {orig_mb:.2f} MB, 现: {comp_mb:.2f} MB, 减少: {percent:.1f}%)",
        "compress_rename_success_path": "原格式压缩成功并替换: {path} (原: {orig_mb:.2f} MB, 现: {comp_mb:.2f} MB)",
        "compress_rename_fail": "重命名临时文件 {temp_filename} 到 {filename} 时失败: {error}。原图已被删除！请手动处理 {temp_filename}！",
        "compress_rename_fail_path": "重命名临时文件 {temp_path} 到 {path} 时失败: {error}。原图已被删除！请手动处理！",
        "compress_unidentified": "无法识别的图片文件或文件已损坏: {filename}，跳过处理。",
        "compress_unidentified_path": "无法识别的图片文件或文件已损坏: {path}，跳过处理。",
        "compress_unidentified_clean_fail": "清理损坏图片产生的临时文件 {path} 失败。",
        "compress_io_error": "处理文件 {filename} 时发生 IO/OS 错误: {error}",
        "compress_io_error_path": "处理文件 {path} 时发生 IO/OS 错误: {error}",
        "compress_unexpected_error": "处理文件 {filename} 时发生未预料的严重错误: {error}\n{traceback}",
        "compress_unexpected_error_path": "处理文件 {path} 时发生未预料的严重错误: {error}",
        "compress_unexpected_error_clean_fail": "清理临时文件 {path} 时失败: {error}",
        # --- WebP 模式特定日志 ---
        "convert_skip_processed": "跳过已处理文件 (根据目录状态 {state_file}): {path}",
        "convert_start": "开始转换为 WebP (替换): {filename} -> {webp_filename}",
        "convert_start_path": "开始转换为 WebP (替换): {path} -> {webp_path}",
        "convert_original_size": "原始文件大小: {size:.2f} MB",
        "convert_get_size_fail": "无法获取文件大小 {filename}: {error}",
        "convert_get_size_fail_path": "无法获取文件大小 {path}: {error}",
        "convert_open_success": "成功打开图片: {path}",
        "convert_webp_options": "WebP 保存选项: quality={quality}, mode={mode} for {path}",
        "convert_webp_options_log": "{filename} -> {webp_filename}: WebP 选项 quality={quality}, mode={mode}",
        "convert_lossless": "无损(Lossless)",
        "convert_lossy": "有损(Lossy)",
        "convert_save_temp_success": "图片成功转换为 WebP 并保存到临时文件: {path}",
        "convert_temp_invalid": "WebP 转换结果无效（临时文件不存在或为空），原图 {filename} 不会被删除。",
        "convert_temp_invalid_path": "WebP 转换结果无效: {path}，原图 {original_path} 不会被删除。",
        "convert_temp_clean_fail": "清理无效临时文件 {path} 时失败: {error}",
        "convert_remove_original_success": "成功删除原图: {path}",
        "convert_remove_original_fail": "删除原图 {filename} 时失败: {error}。转换后的 WebP 文件 {temp_filename} 将被保留。",
        "convert_remove_original_fail_path": "删除原图 {path} 时失败: {error}。临时文件 {temp_path} 被保留。",
        "convert_rename_success": "成功转换为 WebP 并替换: {filename} -> {webp_filename} (原: {orig_mb:.2f} MB, 现: {webp_mb:.2f} MB, 减少: {percent:.1f}%)",
        "convert_rename_success_path": "成功转换为 WebP 并替换: {path} -> {webp_path} (原: {orig_mb:.2f} MB, 现: {webp_mb:.2f} MB)",
        "convert_rename_fail": "重命名临时 WebP 文件 {temp_filename} 到 {webp_filename} 时失败: {error}。原图已被删除！请手动处理 {temp_filename}！",
        "convert_rename_fail_path": "重命名临时 WebP 文件 {temp_path} 到 {webp_path} 时失败: {error}。原图已被删除！请手动处理！",
        "convert_unidentified": "无法识别的图片文件或文件已损坏: {filename}，跳过转换。",
        "convert_unidentified_path": "无法识别的图片文件或文件已损坏: {path}，跳过转换。",
        "convert_unidentified_clean_fail": "清理损坏图片产生的临时文件 {path} 失败。",
        "convert_io_error": "处理文件 {filename} 或写入 WebP 时发生 IO/OS 错误: {error}",
        "convert_io_error_path": "处理文件 {path} 或写入 WebP 时发生 IO/OS 错误: {error}",
        "convert_value_error": "保存 WebP 文件 {webp_filename} 时出错 (可能是不支持的模式或选项): {error}",
        "convert_value_error_path": "保存 WebP 文件 {webp_path} 时出错: {error}",
        "convert_value_error_clean_fail": "清理 WebP 保存失败产生的临时文件 {path} 失败。",
        "convert_unexpected_error": "转换文件 {filename} 到 WebP 时发生未预料的严重错误: {error}\n{traceback}",
        "convert_unexpected_error_path": "转换文件 {path} 到 WebP 时发生未预料的严重错误: {error}",
        "convert_unexpected_error_clean_fail": "清理临时文件 {path} 时失败: {error}",
    },
    'en': {
        # --- General & Setup ---
        "select_language": "Select language (1=中文, 2=English, Default: 中文): ",
        "invalid_choice_language": "Invalid choice, please enter 1, 2 or press Enter.",
        "language_selected": "Language selected: English",
        "select_mode": "Select processing mode (1=Compress Original, 2=Convert to WebP, Default: Convert to WebP): ",
        "invalid_choice_mode": "Invalid choice, please enter 1, 2 or press Enter.",
        "mode_selected": "Processing mode selected: {mode_name}",
        "mode_webp": "Convert to WebP (Replace)",
        "mode_inplace": "Compress Original Format (Keep format & Replace)",
        "prompt_jpeg_quality": "Enter JPEG compression quality (1-95, default: {default}): ",
        "prompt_png_optimize": "Enable PNG optimization? (y/n, default: {default}): ",
        "prompt_webp_quality": "Enter WebP compression quality/strength (0-100, default: {default}): ",
        "prompt_webp_lossless": "Force WebP lossless mode? (y/n, default: {default}): ",
        "error_invalid_quality_jpeg": "Quality must be between 1 and 95.",
        "error_invalid_quality_webp": "Quality must be between 0 and 100.",
        "error_invalid_number": "Please enter a valid number.",
        "error_invalid_yn": "Please enter 'y' or 'n'.",
        "user_interrupt": "User interrupted input.",
        "task_start": "="*30 + " Starting Image Processing Task (Mode: {mode_name}) " + "="*30,
        "target_folder": "Target root folder: {folder}",
        "supported_types": "Supported file types: {extensions}",
        "inplace_config": "Compress Original Format mode config: JPEG Quality={quality}, Large File(>{large_threshold}MB) Quality={large_quality}, PNG Optimization={png_optimize}",
        "inplace_png_optimize_enabled": "Enabled",
        "inplace_png_optimize_disabled": "Disabled",
        "webp_config": "WebP conversion mode config: Quality={quality}, {lossless_mode}",
        "webp_config_lossless_forced": "Forced Lossless",
        "webp_config_lossless_auto": "Default Lossy (PNG/BMP/TIFF tend towards lossless)",
        "state_file_info": "Directory state file: {state_file}, Directory log: {log_file}",
        "scanning_dir": "Scanning directory ({mode_name} mode): {subdir}",
        "dir_processed_count": "Directory {subdir} processed file count (from state file {state_file}): {count}",
        "skip_webp_self": "Skipping WebP file itself: {path}",
        "unhandled_exception": "Caught unhandled exception while calling process function ({path}): {error}",
        "dir_process_complete": "Successfully completed {mode_name} processing for {count} files in directory {subdir}.",
        "user_interrupt_process": "Processing was interrupted by the user.",
        "unexpected_error_process": "An unexpected error occurred during processing.",
        "task_end": "="*30 + " Image Processing Task Finished (Mode: {mode_name}) " + "="*30,
        "summary_processed": "Total files successfully processed in this session: {count}",
        "summary_skipped": "Total files skipped in this session (already processed): {count}",
        "summary_dirs_processed": "Processing operations were performed in {count} directories this session.",
        "summary_errors": "Total files encountered errors or failed processing this session: {count}",
        "summary_size_before": "Total original file size (estimated): {size:.2f} MB",
        "summary_size_after": "Total output file size: {size:.2f} MB",
        "summary_reduction": "Total size reduction approx.: {percent:.2f}%",
        "summary_no_output": "No output files were successfully generated, cannot calculate size reduction percentage.",
        "summary_duration": "Total task duration: {duration:.2f} seconds",
        "summary_global_log": "See global log at: {path}",
        "summary_dir_log": "See {mode_name} mode directory logs in corresponding directories: {log_file}",
        "summary_dir_state": "See {mode_name} mode state records in corresponding directories: {state_file}",
        "error_invalid_path": "Error: Provided path '{path}' is not a valid directory or cannot be accessed.",
        "argparse_description": "Image processing tool: Recursively processes images in a specified directory.\n"
                                "Select processing mode on startup (Default: Convert to WebP, Optional: Compress Original Format).\n"
                                "Supports resumable processing using directory-level state files and logs.",
        "argparse_folder_help": "Path to the root folder containing images to process",
        # --- Log and processing function texts ---
        "log_setup_fail": "Error: Could not set up global log file handler at {path}: {error}",
        "log_dir_write_fail": "Failed to write to directory log {path}: {error}",
        "log_load_state_success": "Successfully loaded {count} records from {path}",
        "log_load_state_fail": "Error loading directory state file {path}: {error}",
        "log_save_state_fail": "Error appending record to directory state file {path} (Original filename: {filename}): {error}",
         # --- Compress Original Format Mode Specific Logs ---
        "compress_skip_processed": "Skipping already processed file (per directory state {state_file}): {path}",
        "compress_start": "Starting original format compression: {filename}",
        "compress_start_path": "Starting original format compression: {path}",
        "compress_file_size": "File size: {size:.2f} MB",
        "compress_get_size_fail": "Cannot get file size for {filename}: {error}",
        "compress_get_size_fail_path": "Cannot get file size for {path}: {error}",
        "compress_open_success": "Successfully opened image: {path}",
        "compress_format_unknown": "Cannot determine image format (extension: {ext}), skipping: {filename}",
        "compress_format_unknown_path": "Cannot determine image format: {path} (extension: {ext}), skipping.",
        "compress_format_identified": "Identified image format: {format} for {path}",
        "compress_large_file": "Detected large file (> {threshold} MB), applying special compression quality: {quality}",
        "compress_large_file_log": "{filename} - Detected large file (> {threshold} MB), applying special compression quality: {quality}",
        "compress_rgba_to_rgb": "Image {path} is RGBA mode, converting to RGB before saving as JPEG.",
        "compress_rgba_to_rgb_log": "Image {filename} is RGBA mode, converting to RGB.",
        "compress_default_save": "Saving with default settings in original format {format}: {path}",
        "compress_save_temp_success": "Image successfully compressed/saved to temporary file: {path}",
        "compress_temp_invalid": "Compression/save result invalid (temp file missing or empty), original file {filename} will not be deleted.",
        "compress_temp_invalid_path": "Compression/save result invalid: {path}, original file {original_path} will not be deleted.",
        "compress_temp_clean_fail": "Failed to clean up invalid temporary file {path}: {error}",
        "compress_remove_original_success": "Successfully deleted original image: {path}",
        "compress_remove_original_fail": "Failed to delete original image {filename}: {error}. Compressed/saved file {temp_filename} will be kept.",
        "compress_remove_original_fail_path": "Failed to delete original image {path}: {error}. Temporary file {temp_path} is kept.",
        "compress_rename_success": "Original format compression successful: {filename} (Orig: {orig_mb:.2f} MB, New: {comp_mb:.2f} MB, Reduced: {percent:.1f}%)",
        "compress_rename_success_path": "Original format compression successful and replaced: {path} (Orig: {orig_mb:.2f} MB, New: {comp_mb:.2f} MB)",
        "compress_rename_fail": "Failed to rename temporary file {temp_filename} to {filename}: {error}. Original file deleted! Please manually handle {temp_filename}!",
        "compress_rename_fail_path": "Failed to rename temporary file {temp_path} to {path}: {error}. Original file deleted! Please manually handle!",
        "compress_unidentified": "Unidentified image file or file corrupted: {filename}, skipping processing.",
        "compress_unidentified_path": "Unidentified image file or file corrupted: {path}, skipping processing.",
        "compress_unidentified_clean_fail": "Failed to clean up temporary file {path} from corrupted image.",
        "compress_io_error": "IO/OS error occurred while processing file {filename}: {error}",
        "compress_io_error_path": "IO/OS error occurred while processing file {path}: {error}",
        "compress_unexpected_error": "Unexpected critical error processing file {filename}: {error}\n{traceback}",
        "compress_unexpected_error_path": "Unexpected critical error processing file {path}: {error}",
        "compress_unexpected_error_clean_fail": "Failed to clean up temporary file {path}: {error}",
        # --- WebP Mode Specific Logs ---
        "convert_skip_processed": "Skipping already processed file (per directory state {state_file}): {path}",
        "convert_start": "Starting WebP conversion (replace): {filename} -> {webp_filename}",
        "convert_start_path": "Starting WebP conversion (replace): {path} -> {webp_path}",
        "convert_original_size": "Original file size: {size:.2f} MB",
        "convert_get_size_fail": "Cannot get file size for {filename}: {error}",
        "convert_get_size_fail_path": "Cannot get file size for {path}: {error}",
        "convert_open_success": "Successfully opened image: {path}",
        "convert_webp_options": "WebP save options: quality={quality}, mode={mode} for {path}",
        "convert_webp_options_log": "{filename} -> {webp_filename}: WebP options quality={quality}, mode={mode}",
        "convert_lossless": "Lossless",
        "convert_lossy": "Lossy",
        "convert_save_temp_success": "Image successfully converted to WebP and saved to temporary file: {path}",
        "convert_temp_invalid": "WebP conversion result invalid (temp file missing or empty), original file {filename} will not be deleted.",
        "convert_temp_invalid_path": "WebP conversion result invalid: {path}, original file {original_path} will not be deleted.",
        "convert_temp_clean_fail": "Failed to clean up invalid temporary file {path}: {error}",
        "convert_remove_original_success": "Successfully deleted original image: {path}",
        "convert_remove_original_fail": "Failed to delete original image {filename}: {error}. Converted WebP file {temp_filename} will be kept.",
        "convert_remove_original_fail_path": "Failed to delete original image {path}: {error}. Temporary file {temp_path} is kept.",
        "convert_rename_success": "Successfully converted to WebP and replaced: {filename} -> {webp_filename} (Orig: {orig_mb:.2f} MB, New: {webp_mb:.2f} MB, Reduced: {percent:.1f}%)",
        "convert_rename_success_path": "Successfully converted to WebP and replaced: {path} -> {webp_path} (Orig: {orig_mb:.2f} MB, New: {webp_mb:.2f} MB)",
        "convert_rename_fail": "Failed to rename temporary WebP file {temp_filename} to {webp_filename}: {error}. Original file deleted! Please manually handle {temp_filename}!",
        "convert_rename_fail_path": "Failed to rename temporary WebP file {temp_path} to {webp_path}: {error}. Original file deleted! Please manually handle!",
        "convert_unidentified": "Unidentified image file or file corrupted: {filename}, skipping conversion.",
        "convert_unidentified_path": "Unidentified image file or file corrupted: {path}, skipping conversion.",
        "convert_unidentified_clean_fail": "Failed to clean up temporary file {path} from corrupted image.",
        "convert_io_error": "IO/OS error occurred while processing file {filename} or writing WebP: {error}",
        "convert_io_error_path": "IO/OS error occurred while processing file {path} or writing WebP: {error}",
        "convert_value_error": "Error saving WebP file {webp_filename} (possibly unsupported mode or options): {error}",
        "convert_value_error_path": "Error saving WebP file {webp_path}: {error}",
        "convert_value_error_clean_fail": "Failed to clean up temporary file {path} from WebP save failure.",
        "convert_unexpected_error": "Unexpected critical error converting file {filename} to WebP: {error}\n{traceback}",
        "convert_unexpected_error_path": "Unexpected critical error converting file {path} to WebP: {error}",
        "convert_unexpected_error_clean_fail": "Failed to clean up temporary file {path}: {error}",
    }
}